baseURL = "http://example.org/"
languageCode = "en-us"
title = "outlets"
theme = "slate"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true
BackgroundStyle = "#1abc9c;"

[[ params.nav ]]
name = "favorites"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "electronics"
tag = "electronics"
icon = "plug"

[[ params.nav ]]
name = "general"
tag = "general"
icon = "shopping-basket"

[[ params.nav ]]
name = "sports"
tag = "sports"
icon = "futbol"