baseURL = "http://example.org/"
languageCode = "en-us"
title = "outlets"
theme = "slate"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "favorites"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "search"
tag = "search"
icon = "search"

[[ params.nav ]]
name = "shopping"
tag = "shopping"
icon = "shopping-basket"

[[ params.nav ]]
name = "music"
tag = "music"
icon = "headphones"

[[ params.nav ]]
name = "video"
tag = "video"
icon = "video-camera"

[[ params.nav ]]
name = "electronics"
tag = "electronics"
icon = "plug"

[[ params.nav ]]
name = "general"
tag = "general"
icon = "shopping-basket"